export const errorMessage = {
  userBanned: 'Tài khoản đã bị khóa',
  usernameAlreadyExist: 'Tài khoản đã tồn tại',
  userIsnotAuthorized: 'Người dùng chưa được xác thực',
  passwordIsRequired: 'Mật khẩu không được để trống',
  passwordHasAtLeast6Character: 'Mật khẩu phải có ít nhất 6 ký tự',
  passwordHasAtLeast1Character: 'Mật khẩu phải có ít nhất 1 ký tự',
  userNotFound: 'Không tìm thấy người dùng',
  userNotExist: 'Tài khoản không tồn tại',
  invalidUsernameOrPassword: 'Sai tài khoản hoặc mật khẩu',
  usernameOrPasswordNotExist: 'Tài khoản hoặc mật khẩu không tồn tại',
  errorInCreateAccount: 'Đã xảy ra lỗi trong quá trình tạo tài khoản, vui lòng thử lại',
  userIsNotAllowedToPerformAction: 'Bạn không có quyền thực hiện hành động này',
  internalServerError: 'Internal Server Error',
  databaseNotInitialize: 'Database not initialized',
  errorInUserService: 'Error in user-service',
  invalidRole: 'Quyền không phù hợp',
  dataInvalid: 'Dữ liệu không hợp lệ',
  usernameHaveAtLeast3Character: 'Tài khoản phải có ít nhất 3 ký tự',
  emailIsNotValid: 'Email không hợp lệ',
  passwordAndRetypePasswordNotSame: 'Mật khẩu và nhập lại mật khẩu phải giống nhau',
  nameHaveAtLeast1Character: 'Tên người dùng phải có tối thiểu 1 ký tự',
  userNotActive: 'Tài khoản chưa được kích hoạt',
  activeStatusNotFound: 'Active status not found in database. Ensure status data is seeded first.',
  invalidStatus: 'Trạng thái bị lỗi',
  errorInProductAdminController: 'Error in ProductAdminController',
  errorInproductService: 'Error in Product Service',
  productNotFound: 'Không tìm thấy sản phẩm',
  errorInUserAdminController: 'Error in User Admin Controller',
  errorInGetUsersInfo: 'Không thể hiển thị người dùng',
  errorInGetUserInfoById: 'Tìm thông tin người dùng bằng mã người dùng thất bại',
  errorInUpdateUserInfo: 'Cập nhật thông tin người dùng không thành công',
  errorInBanUserBaseOnId: 'Khóa tài khoản người dùng không thành công',
  errorInGetAllProducts: 'Không thể hiển thị sản phẩm',
  errorInAddProduct: 'Không thể thêm sản phẩm',
  errorInGetProductById: 'Tìm sản phẩm bằng mã sản phẩm thất bại',
  errorInGetProductByName: 'Tìm sản phẩm bằng tên thất bại',
  errorInDeleteProduct: 'Xóa sản phẩm không thành công',
  invalidUserId: 'Mã người dùng không hợp lệ',
  invalidProductId: 'Mã sản phẩm không hợp lệ',
  fileUploadNotFound: 'Không tìm thấy file upload'
};