export const Strings = {
	username: 'Tài khoản',
	password: 'Mật khẩu',
	signIn: 'Đăng nhập',
	forgotPassword: 'Quên mật khẩu?',
	signUp: 'Đăng ký',
	email: 'Email',
	retypePassword: 'Nhập lại mật khẩu',
  haveAnAccount: 'Đã có tài khoản',
  shopNameLabel: 'Shop Web App',
  profile: 'Tài khoản của tôi',
  order: 'Hóa đơn',
  logout: 'Đăng xuất',
  userProfile: 'Tài khoản người dùng',
  dashboard: 'Bảng thống kê',
  revenue: 'Doanh thu',
  manageInfo: 'Quản lý thông tin',
  userInfoMangament: 'Quản lý thông tin người dùng',
  productMangament: 'Quản lý sản phẩm',
  orderInfoManagement: 'Quản lý thông tin đơn hàng',
  categoryManagement: 'Quản lý danh mục',
};
